### ISSUE TITLE
Unable to build on Simulator with ARM64 Arch

### ISSUE THREAD

**Issue by nurkenn-keda** [WeTransfer/Mocker#144] opened 2023-03-18 09:44 UTC
Re-opened issue  #75 
Can confirm it's still happening on my machine:

Spec:
CPU: M2
Xcode: 14.2
Alamofire: 5.6.4
Target: iPhone 14 Pro Simulator (arm64)

Reverting to Mocker 2.2.0 solved the issue
I used the tutorial in the Readme.md to integrate Mocker

```swift
func test_OK() {
        let configuration = URLSessionConfiguration.af.default
        configuration.protocolClasses = [MockingURLProtocol.self]
        let sessionManager = Alamofire.Session(configuration: configuration)
        
        
        let originalUrl: URL = URL(string: "Some URL")!
        let mock = Mock(url: originalUrl, contentType: .json, statusCode: 200, data: [.post: <Some Data here>])
        mock.register()
        
        let expectation = XCTestExpectation(description: "Create JSON")
        
        Task {
            // Call application code here //
        }
        wait(for: [expectation], timeout: 5.0)
}
```

**Comment by AvdLee** [comment] 2023-03-22 13:28
@nurkenn-keda I'm closing this issue as a duplicate of #75, let's continue there.

**Closed as not planned by AvdLee** 2023-03-22 13:28 UTC
